### ISSUE TITLE
Odd path issue when installing into a prefix

### ISSUE THREAD

**Issue by ftyers** [robertostling/eflomal#8]
I install eflomal into a prefix, as follows:

```
cloud-user@opus-rr:~/guarani/source/eflomal$ python3 setup.py install --prefix=$HOME/guarani/local
running install
running bdist_egg
running egg_info
writing requirements to eflomal.egg-info/requires.txt
writing eflomal.egg-info/PKG-INFO
writing dependency_links to eflomal.egg-info/dependency_links.txt
writing top-level names to eflomal.egg-info/top_level.txt
reading manifest file 'eflomal.egg-info/SOURCES.txt'
writing manifest file 'eflomal.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.4/eflomal.cpython-34m.so -> build/bdist.linux-x86_64/egg
creating stub loader for eflomal.cpython-34m.so
byte-compiling build/bdist.linux-x86_64/egg/eflomal.py to eflomal.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying eflomal.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying eflomal.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying eflomal.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying eflomal.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying eflomal.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.eflomal.cpython-34: module references __file__
creating 'dist/eflomal-0.1-py3.4-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Creating /home/cloud-user/guarani/local/lib/python3.4/site-packages/site.py
Processing eflomal-0.1-py3.4-linux-x86_64.egg
removing '/home/cloud-user/guarani/local/lib/python3.4/site-packages/eflomal-0.1-py3.4-linux-x86_64.egg' (and everything under it)
creating /home/cloud-user/guarani/local/lib/python3.4/site-packages/eflomal-0.1-py3.4-linux-x86_64.egg
Extracting eflomal-0.1-py3.4-linux-x86_64.egg to /home/cloud-user/guarani/local/lib/python3.4/site-packages
eflomal 0.1 is already the active version in easy-install.pth

Installed /home/cloud-user/guarani/local/lib/python3.4/site-packages/eflomal-0.1-py3.4-linux-x86_64.egg
Processing dependencies for eflomal==0.1
Searching for numpy==1.8.2
Best match: numpy 1.8.2
numpy 1.8.2 is already the active version in easy-install.pth

Using /usr/lib/python3/dist-packages
Finished processing dependencies for eflomal==0.1
```

Everything seems to work, and the prefix is in my PYTHONPATH:

```
$ echo $PYTHONPATH
:/home/cloud-user/guarani/local/lib/python3.4/site-packages/
```

But when I try to run it I get the following error:

```
$ cat ../../iterations/grn-spa.0.eflomal
Traceback (most recent call last):
  File "align.py", line 142, in <module>
    if __name__ == '__main__': main()
  File "align.py", line 136, in main
    use_gdb=args.debug)
  File "eflomal.pyx", line 156, in eflomal.align (python/eflomal/eflomal.c:3657)
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cloud-user/guarani/source/eflomal/eflomal'
```

Any ideas?

**Comment by ftyers** [comment]
Oops, forgot to run `make`. Sorry for the noise!
